Feature/afl 56 configure environment
Accult/coworking_ pull request #3
Opened 2023-10-20 12:25 UTC by Accult

Upgraded  to psql

2023-10-20 16:44 UTC, rdchvd requested changes
- [x]  I don't see deleted sqlite DB
- [x]  Add .env-example so users without your creds will know what to create to make the app work

2023-10-20 16:44 UTC, rdchvd commented on coworking_project/settings.py
> +# Завантажте змінні середовища з .env файлу
_and that's what we call lahidna ukrainizacia_
(remove it pls)

2023-10-20 16:44 UTC, rdchvd commented on pyproject.toml
> +psycopg2 = "^2.9.9"
You'd better use  `psycopg2-binary`, as I know `psycopg2` is not great for team, it can cause issues

2023-10-21 10:51 UTC, Accult commented on coworking_project/settings.py
> +# Завантажте змінні середовища з .env файлу
а чого ти доїбалась?
ми з України

2023-10-23 16:56 UTC, rdchvd approved these changes
Good job!!

2023-10-23 16:59 UTC, rdchvd approved these changes

2023-10-23 17:38 UTC, merged